### PR TITLE
Add support for ARM and ARM64

### LINKED ISSUE #437: ARM/ARM64 not supported as values to --platform flag
We need to build for ARM/ARM64 as platforms (as well as potentially other platforms names for different Android, iOS, etc... project types).

However, it appears that the list of values passed into the `--platforms` argument of the `slngen` tool is first scrubbed, and anything beyond x86, x64, any cpu is effectively scrubbed:

https://github.com/microsoft/slngen/blob/f99e2e942dfc518f4f99a7acd847f06e03714e17/src/Microsoft.VisualStudio.SlnGen/SlnFile.cs#L542-L563

----

I assume this function is used by the `slngen` tool in addition to the msbuild target mode, as that's the behavior I'm seeing on the command line:

```
dotnet slngen --platform "ARM64"
```

image

----

This is a blocking issue for us adopting this tool in our workflow, everything else currently appears to be working fine.

The simplest solution would allow custom values by not making everything falling out of the switch statement go to `null` but instead pass through the original `platform` value.

### PR DESCRIPTION
**Pull request by jeffkl**
Fixes #437

### CODE REVIEW

**Comment by michael-hawker** [comment]
Thanks @jeffkl!

Any thoughts on it still returning `null` and ignoring other values? This may matter on other platforms like Android/iOS, I know Uno Platform does stuff here in this space.

**Comment by jeffkl** [comment]
> Any thoughts on it still returning null and ignoring other values? This may matter on other platforms like Android/iOS, I know Uno Platform does stuff here in this space.

Can you elaborate more?  What values would return `null`?  At the moment SlnGen only emits stuff in the solution for configurations and platforms that it understands.  From what I remember, this is what Visual Studio does if you use some custom values that it doesn't understand.

**Comment by michael-hawker** [comment]
@jeffkl I can type anything in the Platform dialog:

image

I was also, previously to this commit, trying to pass ARM64 in:

    dotnet slngen --platform "Any CPU;x64;x86;ARM64"

But that gets stripped by the `null`.

If there are custom tooling/msbuild sdks, etc... that may be used by a project, they may care about non-standard platforms, like the Uno Platform iOS ones:

image

**Comment by jeffkl** [comment]
@michael-hawker this is extremely complicated from the command-line.  Visual Studio has two concepts:  **Solution** configuration and **Project** configuration.  The hard part is mapping _project_ configurations to _solution_ configurations.  When you use the UI, you get a nice grid and can create a solution platform and map it to the appropriate project platform.  In some cases you'll want to create a solution configuration like "Custom Thing" but when you build it you want to map that to "x86" for the project.

Since SlnGen is a command-line tool, I haven't found a good way for a user to convey these mappings.  At the moment, there are some built-in mappings for C++ projects, when you select a solution platform of Any CPU, it will build x86 or amd64 if the project supports one of those.

What works best is for the projects to convey what they support which is how SlnGen dynamically discovers configurations and platforms.  If an SDK-style CSPROJ has:

```xml
<PropertyGroup>
  <Platforms>AnyCPU;x86;x64</Platforms>
</PropertyGroup>
```

Then SlnGen will generate a solution with the correct **solution** platforms and map it to the **project** platforms.  What's missing is any way to convey a mapping.  I'm not sure if its worth it at the moment but we could look into something like:

```xml
<ItemGroup>
  <SlnGenSolutionPlatform Condition="'$(Platform)' == 'x64'">MyCustomPlatform</SlnGenSolutionPlatform>
</ItemGroup>
```

But I'm not sure how many people need this functionality.  In the 5 years that I've worked on SlnGen, no one has asked for custom mappings like this...

**Pull request merged**
