### PR TITLE
Add .NET 9 support

### PR DESCRIPTION
**Pull request by RussKie**
Similar to #425 and #472

### CODE REVIEW

**Comment by RussKie** [comment]
@jeffkl this built successfully; however, I'm having troubles while testing the artifact:
```
PS D:\Development\dotnet-extensions> ./scripts/Slngen.ps1 -All -NoLaunch
You must install or update .NET to run this application.

App: C:\Users\user\.nuget\packages\microsoft.visualstudio.slngen.tool\11.0.9-gfa512211b6\tools\slngen\net9.0\slngen.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '9.0.0-any' (x64)
.NET location: D:\Development\dotnet-extensions\.dotnet\

The following frameworks were found:
  6.0.22 at [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  8.0.0-rc.1.23414.4 at [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  ....
  9.0.0-alpha.1.23527.10 at [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=9.0.0-any&arch=x64&rid=win-x64&os=win10
```

Microsoft.NETCore.App/9.0.0-alpha.1.23527.10 is what shipped with SDK 9.0.100-alpha.1.23528.2.

Any ideas what's missing?

**Comment by jeffkl** [comment]
@RussKie what does the contents of `slngen.runtimeconfig.json` look like?  That would control which runtime it runs on

**Comment by jeffkl** [comment]
I've fixed the problem, apparently my hack of `major.minor.build-any` was no good for alpha releases.  `-alpha` appears to work for both .NET 9 which is alpha and .NET 8 which is RC. 🤷 

I also added a missing property so that the global tool builds the .NET 9 instance properly.

**Review by jeffkl — APPROVED** [review]
Thank you for the contribution!

**Comment by RussKie** [comment]
Thank you @jeffkl!

**Pull request merged**
