### PR TITLE
Added a new parameter to ignore special treatment of the main project

### PR DESCRIPTION
**Pull request by Portikus**
#151

### CODE REVIEW

**Comment by jeffkl** [comment]
Looks great, please add a unit test and I'll merge it

**Comment by Portikus** [comment]
Ofcorse 👍 
Added unit tests.

**Comment by stijnherreman** [comment]
@jeffkl this parameter is not yet documented. It's also inconsistent by using camel case and not taking a value (`CommandOptionType.NoValue`).
Can I include fixes for the inconsistency in a PR, or would you prefer just documenting the current implementation?

**Comment by jeffkl** [comment]
@stijnherreman contributions are always welcome, please open a new issue and feel free to send a PR.  Thanks!

**Pull request merged**
